### ISSUE TITLE
load jitterentropy_rng kernel module using the kernel command line / kernel built-in jitterentropy_rng?

### ISSUE THREAD

**Issue by adrelanos** [smuellerDD/jitterentropy-rngd#9]
I hope it is OK to use this place for asking questions.

In the Whonix Linux distribution (a Debian derivative) we've enabled loading the `jitterentropy_rng` kernel module by default.

https://github.com/Whonix/security-misc

https://github.com/Whonix/security-misc/blob/master/usr/lib/modules-load.d/30_security-misc.conf

Is it possible / advisable / discouraged to compile the jitterentropy_rng kernel module as built-in. (kernel config "y" rather than kernel config "m")

Also since it will take us a while to compile a custom kernel and ship for all users (VMs, host, ...) I have another related question...

Is it possible / advisable / discouraged to load the jitterentropy_rng kernel module using the kernel command line? Would it then load more early than if we used `/usr/lib/modules-load.d`?

**Comment by smuellerDD** [comment]
Am Samstag, 30. November 2019, 08:45:57 CET schrieb Patrick Schleizer:

Hi Patrick,

> I hope it is OK to use this place for asking questions.

Always.
> 
> In the Whonix Linux distribution (a Debian derivative) we've enabled loading
> the `jitterentropy_rng` kernel module by default.
> 
> https://github.com/Whonix/security-misc
> 
> https://github.com/Whonix/security-misc/blob/master/usr/lib/modules-load.d/3
> 0_security-misc.conf
> 
> Is it possible / advisable / discouraged to compile the jitterentropy_rng
> kernel module as built-in. (kernel config "y" rather than kernel config
> "m")

Maybe we need to get back to understand why there is a Jitter RNG instance in 
the kernel. 

This instance is currently (barring the acceptance of [1]) only used to seed 
the in-kernel DRBG in case the driver/char/random.c is not yet fully seeded.

It currently has no other use case. In particular, it is not linked with 
random.c and thus feeds /dev/random or /dev/urandom.

The in-kernel DRBG currently is only used to support the IV generation as part 
of IPSEC.

That said, I guess you can answer your question now yourself: if you need the 
in-kernel DRBG, you want the jitterentropy_rng statically in the kernel. 
Otherwise not.

> 
> Also since it will take us a while to compile a custom kernel and ship for
> all users (VMs, host, ...) I have another related question...
> 
> Is it possible / advisable / discouraged to load the jitterentropy_rng
> kernel module using the kernel command line? Would it then load more early
> than if we used `/usr/lib/modules-load.d`?

Given the answer above, I think it is clear that building it as a module will 
most likely defeat the intent of it. Yet, if it is compiled as a module, the 
kernel crypto API will try to invoke modprobe to load it when it is needed. 
Thus, any invocation of insmod/modprobe from user space is moot.

[1] https://www.chronox.de/lrng.html

Ciao
Stephan

**Comment by adrelanos** [comment]
Are you aware of examples of users (other kernel modules, kernel functions, software packages) that make use of in-kernel DRBG?

I was searching for `#include <crypto/drbg.h>` to find some Open Source examples but no luck.

**Comment by smuellerDD** [comment]
> Am 01.02.2020 um 04:32 schrieb Patrick Schleizer <notifications@github.com>:
> 
> Are you aware of examples of users (other kernel modules, kernel functions, software packages) that make use of in-kernel DRBG?

Search for „stdrng“ in the kernel. This will use the DRBG. E.g. the IV generators use it.

Besides, I am using it with my LRNG [1].

[1] https://www.chronox.de/lrng.html
